[default]
db = "faucet"
default_login_redirect_uri = "https://127.0.0.1:3030/"

[global.oauth.twitter]
provider = "twitter"
client_id = "<client_id>"
client_secret = "<client_secret>"
redirect_uri = "https://127.0.0.1:3000/"

[global.tls]
certs = "<path/tls/cert.pem>"
key = "<path/tls/key.pem>"