[default]
db = "faucet"
mnemonic="<mnemonic>"
time_to_wait_between_claims = { secs = 0, nanos = 0 }
native_token_amount = 0.5
token_amount = 10

[global.oauth.twitter]
provider = "twitter"
client_id = "<client_id>"
client_secret = "<client_secret>"
redirect_uri = "http://localhost:3000"
