[default]
db = "faucet"
default_login_redirect_uri = "http://localhost:3000/"

[global.oauth.twitter]
provider = "twitter"
client_id = "<client_id>"
client_secret = "<client_secret>"
redirect_uri = "http://localhost:3000"
