[default]
db = "faucet"
mnemonic="<mnemonic>"
time_to_wait_between_claims = { secs = 30, nanos = 0 }
token_amount = 20
native_token_amount = 3
verify_following_webb = false
tx_timeout = 30000

[global.oauth.twitter]
provider = "twitter"
client_id = "<client_id>"
client_secret = "<client_secret>"
redirect_uri = "http://localhost:3000"
